### ISSUE TITLE
Widget not showing on Firefox Developer Edition

### ISSUE THREAD

**Issue by ManuRodgers** [marsidev/react-turnstile#19] opened 2023-04-19 01:55 UTC
![image](https://user-images.githubusercontent.com/33333844/232946337-6eaaf634-2d5f-486f-b2be-afd00864472b.png)
based on the picture above, the widget can be displayed normal in google chrome and safari, but it cannot be normally displayed in firefox developer edition right now. and it shows

**Comment by marsidev** [comment] 2023-04-19 23:49
Hey @ManuRodgers, I could not reproduce this error. Are you using a custom config? Any context info could be helpful.
![image](https://user-images.githubusercontent.com/56328053/233223129-2ca202f8-4443-45c7-9a70-6234e55558df.png)

**Comment by ManuRodgers** [comment] 2023-04-20 00:03
I cannot reproduce that error at this moment in Firefox developer edition browser too. `  <Turnstile
          onError={() => {
            console.log("has Turnstile error");
          }}
          siteKey="3x00000000000000000000FF"
          onSuccess={setTurnstileToken}
          options={{
            theme: "light",
          }}
        />`
the above code is context info you need

**Comment by marsidev** [comment] 2023-04-20 00:22
I'll close this issue as seems is working properly in Firefox Developer Edition.

**Closed by marsidev** 2023-04-20 00:22 UTC
Labels: bug
