### ISSUE TITLE
Turnstile opens Source tab in the console

### ISSUE THREAD

**Issue by stanislavlyu** [marsidev/react-turnstile#38] opened 2023-09-21 16:18 UTC
**bug**

**After I added Turnstile to my web app I noticed that my Source tab is being opened automatically. I don’t have any debugger attached, or any debugger keyword in the codebase. I also tested the app in incognito mode(no extensions) - same thing. Does anybody have any ideas?**

**import { Turnstile, SCRIPT_URL, DEFAULT_SCRIPT_ID } from '@marsidev/react-turnstile';
import Script from 'next/script';
export default function Widget() {
  const siteKey = process.env.NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY as string;
  return (
    <div>
      <Script id={DEFAULT_SCRIPT_ID} src={SCRIPT_URL} strategy='afterInteractive' />
      <Turnstile
        injectScript={false}
        siteKey={siteKey}
        className='turnstile-widget'
        options={{
          theme: 'light',
        }}
      />
    </div>
  );
}
**

**Don't show source tab after reload the page**

https://github.com/marsidev/react-turnstile/assets/101093960/f9b40b28-e766-4bc5-82cf-a2be4dbe31b2

**Comment by marsidev** [comment] 2023-09-22 12:45
Hey! Thanks for sharing. I don't see that happening on [this demo](https://react-turnstile.vercel.app/manual-script-injection). Can you please replicate the bug in a codesandbox?

**Comment by tjmcewan** [comment] 2023-09-30 12:24
I'm using version `0.3.1` and am seeing this issue in chrome & ungoogled chromium on the latest versions as of this comment.

Btw, I am seeing it on that demo if I change the Site Key Type to "Force Interactive Challenge".

Thanks!

**Comment by marsidev** [comment] 2023-10-02 16:36
Hey guys,

As you mention, @tjmcewan, the error happens if we set the sitekey type to _Force interactive challenge_.

I noticed this error also happens when using vanilla turnstile ([check this](https://friendly-broccoli-phi.vercel.app/)), so I submitted an issue here: https://community.cloudflare.com/t/debugger-opens-when-sitekey-is-3x00000000000000000000ff/564400

I'll close this issue since the issue is nothing to do with this library.

**Closed by marsidev** 2023-10-02 16:36 UTC

**Comment by humbletoymaker** [comment] 2025-03-29 10:08
Doesn't seem to happen using vanilla Turnstile anymore: https://friendly-broccoli-phi.vercel.app
However, I'm still seeing this happening in the react library, unfortunately. Could you please see if this is also the case for you @marsidev?

**Comment by marsidev** [comment] 2025-03-31 18:28
Sorry but I cannot reproduce it anymore. Feel free to open a new issue with reproduction steps @humbletoymaker

**Comment by MylesWardell** [comment] 2025-11-11 00:18
I am also seeing this in the console which is very odd as we turn off non error logs in production

<img width="2253" height="1316" alt="Image" src="https://github.com/user-attachments/assets/b47c98c0-7fd2-47f6-a07b-fea8a2d4d3d9" />
